name: 'Determine SonarQube Variables'
description: 'Calculate SonarQube project key and reference branch based on git context'
inputs:
  default-reference-branch:
    description: 'Default reference branch for new code detection'
    required: false
    default: 'development'
  pr-base-ref:
    description: 'Pull request base ref (from github.event.pull_request.base.ref)'
    required: false
    default: ''
  current-branch:
    description: 'Current branch name (from github.ref_name)'
    required: false
    default: ''
  project-prefix:
    description: 'Project name prefix (e.g., "humango-mobile" or "humango-backend")'
    required: true

outputs:
  reference-branch:
    description: 'Computed SonarQube reference branch'
    value: ${{ steps.compute.outputs.reference-branch }}
  project-key:
    description: 'Computed SonarQube project key'
    value: ${{ steps.compute.outputs.project-key }}

runs:
  using: 'composite'
  steps:
    - id: compute
      shell: bash
      run: |
        set -e
        
        REF_BRANCH="${{ inputs.default-reference-branch }}"
        
        # If this is a PR, use the PR destination branch
        if [ -n "${{ inputs.pr-base-ref }}" ]; then
          REF_BRANCH="${{ inputs.pr-base-ref }}"
        fi
        
        # Determine project key based on branch
        if [[ "$REF_BRANCH" == "master" ]] || [[ "${{ inputs.current-branch }}" == "master" ]]; then
          REF_BRANCH="master"
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}-master"
        elif [[ "$REF_BRANCH" == release/* ]] || [[ "${{ inputs.current-branch }}" == release/* ]] || [[ "$REF_BRANCH" == releases/* ]] || [[ "${{ inputs.current-branch }}" == releases/* ]]; then
          # For release branches
          if [[ "$REF_BRANCH" != release/* && "$REF_BRANCH" != releases/* ]]; then
            # Get the latest release branch
            git fetch --prune origin '+refs/heads/release/*:refs/remotes/origin/release/*' '+refs/heads/releases/*:refs/remotes/origin/releases/*' >/dev/null 2>&1 || true
            DETECTED_REF_BRANCH=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin/release/ refs/remotes/origin/releases/ 2>/dev/null | head -n1)
            echo "Detected latest release branch: $DETECTED_REF_BRANCH"
            if [[ -n "$DETECTED_REF_BRANCH" ]]; then
              REF_BRANCH=${DETECTED_REF_BRANCH#origin/}
            else
              echo "No release/* branch found"
            fi
          fi
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}-release"
        else
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}"
        fi
        
        echo "Reference branch: $REF_BRANCH"
        echo "SonarQube Project Key: $SONAR_PROJECT_KEY"
        
        echo "reference-branch=$REF_BRANCH" >> $GITHUB_OUTPUT
        echo "project-key=$SONAR_PROJECT_KEY" >> $GITHUB_OUTPUT
