name: 'Determine SonarQube Variables'
description: 'Calculate SonarQube project key and reference branch based on git context'
inputs:
  default-reference-branch:
    description: 'Default reference branch for new code detection'
    required: false
    default: 'development'
  pr-base-ref:
    description: 'Pull request base ref (from github.event.pull_request.base.ref)'
    required: false
    default: ''
  current-branch:
    description: 'Current branch name (from github.ref_name)'
    required: false
    default: ''
  gcloud-project:
    description: 'GCP project name (from GCLOUD_PROJECT)'
    required: false
    default: 'humango-dev-4'
  project-prefix:
    description: 'Project name prefix (e.g., "humango-mobile" or "humango-backend")'
    required: true

outputs:
  reference-branch:
    description: 'Computed SonarQube reference branch'
    value: ${{ steps.compute.outputs.reference-branch }}
  project-key:
    description: 'Computed SonarQube project key'
    value: ${{ steps.compute.outputs.project-key }}

runs:
  using: 'composite'
  steps:
    - id: compute
      shell: bash
      run: |
        set -e
        
        REF_BRANCH="${{ inputs.pr-base-ref }}"
        if [ -z "$REF_BRANCH" ]; then
          REF_BRANCH="${{ inputs.default-reference-branch }}"
        fi

        REF_GCP_PROJECT="${{ inputs.gcloud-project }}"

        # Determine project key based on branch and environment
        if [[ "$REF_BRANCH" == "master" ]]; then
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}-master"
        elif [[ "$REF_BRANCH" == *"release/"* ]] || [[ "${{ inputs.current-branch }}" == *"release/"* ]] || [[ "$REF_GCP_PROJECT" == *"humango-alpha"* ]]; then
          # For release branches or alpha environments
          if [[ "$REF_BRANCH" != *"release/"* ]]; then
            # Get the latest release/historical branch
            git fetch --prune origin '+refs/heads/release/*:refs/remotes/origin/release/*' >/dev/null 2>&1 || true
            git fetch --prune origin '+refs/heads/historical/*:refs/remotes/origin/historical/*' >/dev/null 2>&1 || true
            DETECTED_REF_BRANCH=$(git for-each-ref --sort=-committerdate --format='%(refname:short)' \
              refs/remotes/origin/release/ \
              refs/remotes/origin/historical/ \
              2>/dev/null | head -n1)
            echo "Detected latest release/historical branch: $DETECTED_REF_BRANCH"
            if [[ -n "$DETECTED_REF_BRANCH" ]]; then
              REF_BRANCH=${DETECTED_REF_BRANCH#origin/}
            else
              echo "No release/* branch found"
            fi
          fi
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}-release"
        else
          SONAR_PROJECT_KEY="${{ inputs.project-prefix }}"
        fi

        echo "Using reference branch: $REF_BRANCH for sonarqube new code detection"
        echo "Using SONAR Project Key: $SONAR_PROJECT_KEY"
        
        echo "reference-branch=$REF_BRANCH" >> $GITHUB_OUTPUT
        echo "project-key=$SONAR_PROJECT_KEY" >> $GITHUB_OUTPUT
