name: Commit Drift Check

on:
  workflow_call:
    inputs:
      max_behind:
        type: number
        default: 5
      max_ahead:
        type: number
        default: 50        

jobs:
  drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - name: Compute drift
        id: drift
        env:
          BASE_REF: ${{ github.base_ref }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          TARGET_REF="HEAD"

          # if BASE_REF or PR_HEAD_REF is empty, it means that workflow was triggered by a non-PR event so behind and ahead are 0 and we move to next step
          if [ -z "$BASE_REF" ] || [ -z "$PR_HEAD_REF" ]; then
            echo "No pull request context, skipping drift check"
            echo "behind=0" >> $GITHUB_OUTPUT
            echo "ahead=0" >> $GITHUB_OUTPUT
            echo "target_ref=$TARGET_REF" >> $GITHUB_OUTPUT
            echo "base_ref=$BASE_REF" >> $GITHUB_OUTPUT
            exit 0
          fi

          git fetch origin "$PR_HEAD_REF"
          TARGET_REF="origin/$PR_HEAD_REF"

          BEHIND=$(git rev-list --count "$TARGET_REF".."origin/$BASE_REF")
          AHEAD=$(git rev-list --count "origin/$BASE_REF".."$TARGET_REF")

          echo "behind=$BEHIND" >> $GITHUB_OUTPUT
          echo "ahead=$AHEAD" >> $GITHUB_OUTPUT
          echo "target_ref=$TARGET_REF" >> $GITHUB_OUTPUT
          echo "base_ref=$BASE_REF" >> $GITHUB_OUTPUT

          echo "Base branch: $BASE_REF"
          echo "Current branch/ref: $TARGET_REF"
          echo "Behind: $BEHIND"
          echo "Ahead: $AHEAD"

      - name: Drift summary
        run: |
          BEHIND="${{ steps.drift.outputs.behind }}"
          AHEAD="${{ steps.drift.outputs.ahead }}"
          TARGET_REF="${{ steps.drift.outputs.target_ref }}"
          BASE_REF="${{ steps.drift.outputs.base_ref }}"
          MAX_BEHIND="${{ inputs.max_behind }}"
          MAX_AHEAD="${{ inputs.max_ahead }}"

          {
            echo "### Commit Drift Check"
            echo
            echo "- Base branch: $BASE_REF"
            echo "- Current branch/ref: $TARGET_REF"
            echo "- Behind: $BEHIND (limit: $MAX_BEHIND)"
            echo "- Ahead: $AHEAD (limit: $MAX_AHEAD)"
            echo
            echo "A limit of 0 means that check is disabled."
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Fail if limits exceeded
        run: |
          if [ "${{ inputs.max_behind }}" -gt 0 ] && [ "${{ steps.drift.outputs.behind }}" -gt "${{ inputs.max_behind }}" ]; then
            echo "❌ Branch is too far behind base"
            exit 1
          fi

          if [ "${{ inputs.max_ahead }}" -gt 0 ] && [ "${{ steps.drift.outputs.ahead }}" -gt "${{ inputs.max_ahead }}" ]; then
            echo "❌ PR has too many commits"
            exit 1
          fi