name: Test Shared Actions

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  drift:
    uses: TeamGenius/humango-PUBLIC-ci-workflows/.github/workflows/commit-drift-check.yml@master
    with:
      max_behind: 10
      max_ahead: 50